### ISSUE TITLE
"At-Will" Spells Don't Appear in Panel

### ISSUE THREAD

**Issue by n-depinto** [teroparvinen/foundry-action-pack#13] opened 2022-12-08 18:54 UTC
Thanks for the awesome module!

I have noticed that spells with the "At-Will" preparation mode don't appear in the panel. Not sure if this was intentional, but would it be possible to have these spells show up on the panel, as well?

**Comment by teroparvinen** [comment] 2022-12-08 20:18
Duplicate of #12

**Comment by teroparvinen** [comment] 2022-12-08 20:18
This is fixed and will be in the next update

**Closed by teroparvinen** 2022-12-08 20:18 UTC

**Comment by n-depinto** [comment] 2022-12-08 22:35
Amazing! Thank you for your work!
